# Generated by Django 4.2.19 on 2025-03-13 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Epreuve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Est actif"),
                ),
                (
                    "max_score",
                    models.IntegerField(default=10, verbose_name="Note maximum"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="exam_files/",
                        verbose_name="Fichier d'epreuve",
                    ),
                ),
                ("duration", models.IntegerField(verbose_name="Durée (minutes)")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.course",
                        verbose_name="Cours",
                    ),
                ),
            ],
            options={
                "verbose_name": "Épreuve",
                "verbose_name_plural": "Épreuves",
            },
        ),
        migrations.CreateModel(
            name="Examen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("date", models.DateTimeField(verbose_name="Date d'examen")),
                (
                    "pass_mark",
                    models.IntegerField(default=5, verbose_name="Score de passage"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Exam",
                "verbose_name_plural": "Exams",
            },
        ),
        migrations.CreateModel(
            name="QuestionExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Question Content")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("short_answer", "Short Answer"),
                        ],
                        default="multiple_choice",
                        max_length=20,
                        verbose_name="Question Type",
                    ),
                ),
                ("score", models.IntegerField(default=1, verbose_name="Score")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "epreuve",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="examen.epreuve",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Question",
                "verbose_name_plural": "Exam Questions",
            },
        ),
        migrations.CreateModel(
            name="Soumission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("soumission_date", models.DateTimeField(auto_now=True)),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="examen.epreuve"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soumission",
                "verbose_name_plural": "Soumissions",
            },
        ),
        migrations.CreateModel(
            name="ResultatExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.FloatField(blank=True, null=True, verbose_name="Score"),
                ),
                (
                    "is_passed",
                    models.BooleanField(default=False, verbose_name="Is Passed"),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reponse_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Réponse de l'élève"
                    ),
                ),
                (
                    "corrected_by_teacher",
                    models.BooleanField(
                        default=False, verbose_name="Corrigé par l'enseignant"
                    ),
                ),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examen.epreuve",
                        verbose_name="Épreuve",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.student",
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Result",
                "verbose_name_plural": "Exam Results",
            },
        ),
        migrations.CreateModel(
            name="ReponseExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Answer Content")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Is Correct"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="examen.questionexamen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Answer",
                "verbose_name_plural": "Exam Answers",
            },
        ),
        migrations.AddField(
            model_name="epreuve",
            name="examen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="epreuves",
                to="examen.examen",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="epreuve",
            unique_together={("examen", "course")},
        ),
    ]
