# Generated by Django 4.2.19 on 2025-03-06 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0006_remove_course_level"),
        ("accounts", "0019_fcmtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="Examen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("date", models.DateTimeField(verbose_name="Date d'examen")),
                ("duration", models.IntegerField(verbose_name="Durée (minutes)")),
                (
                    "max_score",
                    models.IntegerField(default=100, verbose_name="Score maximum"),
                ),
                (
                    "pass_mark",
                    models.IntegerField(default=50, verbose_name="Score de passage"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Est actif"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="exam_files/",
                        verbose_name="Fichier d'examen",
                    ),
                ),
                (
                    "courses",
                    models.ManyToManyField(to="course.course", verbose_name="Cours"),
                ),
            ],
            options={
                "verbose_name": "Exam",
                "verbose_name_plural": "Exams",
            },
        ),
        migrations.CreateModel(
            name="QuestionExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Question Content")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("short_answer", "Short Answer"),
                        ],
                        default="multiple_choice",
                        max_length=20,
                        verbose_name="Question Type",
                    ),
                ),
                ("score", models.IntegerField(default=1, verbose_name="Score")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.course",
                        verbose_name="Cours",
                    ),
                ),
                (
                    "examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="examen.examen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Question",
                "verbose_name_plural": "Exam Questions",
            },
        ),
        migrations.CreateModel(
            name="ResultatExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(verbose_name="Score")),
                (
                    "is_passed",
                    models.BooleanField(default=False, verbose_name="Is Passed"),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.course",
                        verbose_name="Cours",
                    ),
                ),
                (
                    "examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examen.examen",
                        verbose_name="Exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.student",
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Result",
                "verbose_name_plural": "Exam Results",
            },
        ),
        migrations.CreateModel(
            name="ReponseExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Answer Content")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Is Correct"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="examen.questionexamen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Answer",
                "verbose_name_plural": "Exam Answers",
            },
        ),
    ]
