# Generated by Django 5.1 on 2025-02-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mychatapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="room",
            field=models.CharField(max_length=1000000),
        ),
    ]
