# Generated by Django 4.2.19 on 2025-03-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsandevents",
            name="posted_as",
            field=models.CharField(
                choices=[("News", "News"), ("Event", "Event")],
                max_length=10,
                verbose_name="¨Poster comme",
            ),
        ),
        migrations.AlterField(
            model_name="newsandevents",
            name="summary",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="Résumé"
            ),
        ),
        migrations.AlterField(
            model_name="newsandevents",
            name="summary_en",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="Résumé"
            ),
        ),
        migrations.AlterField(
            model_name="newsandevents",
            name="summary_es",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="Résumé"
            ),
        ),
        migrations.AlterField(
            model_name="newsandevents",
            name="summary_fr",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="Résumé"
            ),
        ),
        migrations.AlterField(
            model_name="newsandevents",
            name="summary_ru",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="Résumé"
            ),
        ),
        migrations.AlterField(
            model_name="newsandevents",
            name="title",
            field=models.CharField(max_length=200, null=True, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="newsandevents",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="newsandevents",
            name="title_es",
            field=models.CharField(max_length=200, null=True, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="newsandevents",
            name="title_fr",
            field=models.CharField(max_length=200, null=True, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="newsandevents",
            name="title_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="Titre"),
        ),
    ]
