# Generated by Django 4.2.19 on 2025-03-13 18:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("title_fr", models.CharField(max_length=200, null=True)),
                ("title_es", models.CharField(max_length=200, null=True)),
                ("title_ru", models.CharField(max_length=200, null=True)),
                ("code", models.CharField(max_length=200, unique=True)),
                ("credit", models.IntegerField(blank=True, default=1)),
                ("summary", models.TextField(blank=True, max_length=200)),
                ("summary_en", models.TextField(blank=True, max_length=200, null=True)),
                ("summary_fr", models.TextField(blank=True, max_length=200, null=True)),
                ("summary_es", models.TextField(blank=True, max_length=200, null=True)),
                ("summary_ru", models.TextField(blank=True, max_length=200, null=True)),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("Premier", " Premier"),
                            ("Deuxième", "Deuxième"),
                            ("Troisième", "Troiième"),
                        ],
                        max_length=200,
                    ),
                ),
                ("is_elective", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, unique=True)),
                ("title_en", models.CharField(max_length=150, null=True, unique=True)),
                ("title_fr", models.CharField(max_length=150, null=True, unique=True)),
                ("title_es", models.CharField(max_length=150, null=True, unique=True)),
                ("title_ru", models.CharField(max_length=150, null=True, unique=True)),
                ("summary", models.TextField(blank=True)),
                ("summary_en", models.TextField(blank=True, null=True)),
                ("summary_fr", models.TextField(blank=True, null=True)),
                ("summary_es", models.TextField(blank=True, null=True)),
                ("summary_ru", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UploadVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_en", models.CharField(max_length=100, null=True)),
                ("title_fr", models.CharField(max_length=100, null=True)),
                ("title_es", models.CharField(max_length=100, null=True)),
                ("title_ru", models.CharField(max_length=100, null=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "video",
                    models.FileField(
                        help_text="Valid video formats: mp4, mkv, wmv, 3gp, f4v, avi, mp3",
                        upload_to="course_videos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["mp4", "mkv", "wmv", "3gp", "f4v", "avi", "mp3"]
                            )
                        ],
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("summary_en", models.TextField(blank=True, null=True)),
                ("summary_fr", models.TextField(blank=True, null=True)),
                ("summary_es", models.TextField(blank=True, null=True)),
                ("summary_ru", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_en", models.CharField(max_length=100, null=True)),
                ("title_fr", models.CharField(max_length=100, null=True)),
                ("title_es", models.CharField(max_length=100, null=True)),
                ("title_ru", models.CharField(max_length=100, null=True)),
                (
                    "file",
                    models.FileField(
                        help_text="Valid Files: pdf, docx, doc, xls, xlsx, ppt, pptx, zip, rar, 7zip",
                        upload_to="course_files/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "pdf",
                                    "docx",
                                    "doc",
                                    "xls",
                                    "xlsx",
                                    "ppt",
                                    "pptx",
                                    "zip",
                                    "rar",
                                    "7zip",
                                ]
                            )
                        ],
                    ),
                ),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dep_head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.departmenthead",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        related_name="allocated_course", to="course.course"
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocated_lecturer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.session",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="course.upload",
                    ),
                ),
                (
                    "upload_video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="course.uploadvideo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
