# Generated by Django 5.1 on 2025-03-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="level",
        ),
    ]
