# Generated by Django 4.2.19 on 2025-03-10 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_remove_course_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="program",
        ),
    ]
