# Generated by Django 4.2.19 on 2025-03-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_remove_course_program"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="year",
        ),
        migrations.AlterField(
            model_name="course",
            name="credit",
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.CharField(
                choices=[
                    ("Premier", " Premier"),
                    ("Deuxième", "Deuxième"),
                    ("Troisième", "Troiième"),
                ],
                max_length=200,
            ),
        ),
    ]
