# Generated by Django 5.1.6 on 2025-02-11 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_usersession"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
