# Generated by Django 5.1.6 on 2025-02-11 21:57

import accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="usersession",
            name="login_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
