# Generated by Django 5.1 on 2025-02-18 01:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_user_bio_remove_user_last_activity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="last_activity",
        ),
        migrations.AddField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
