# Generated by Django 5.1 on 2025-02-20 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_remove_student_last_activity_user_last_activity"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("course_registration", "Inscription à un cours"),
                            ("quiz_completion", "Quiz terminé"),
                            ("login", "Connexion"),
                            ("logout", "Déconnexion"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_logs",
                        to="accounts.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Log",
                "verbose_name_plural": "Student Logs",
                "ordering": ("-timestamp",),
            },
        ),
    ]
