# Generated by Django 5.1 on 2025-02-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_studentlogs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="level",
        ),
    ]
