# Generated by Django 5.1 on 2025-02-27 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_remove_student_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="relation_ship",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Père", "Père"),
                    ("Mère", "Mère"),
                    ("Frère", "Frère"),
                    ("Soeur", "Soeur"),
                    ("Grand-mère", "Grand-mère"),
                    ("Grand-père", "Grand-père"),
                    ("Autre", "Autre"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculin"), ("F", "Féminin")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecturer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
