# Generated by Django 5.1 on 2025-02-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_parent_relation_ship_alter_user_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturer",
            name="students",
            field=models.ManyToManyField(blank=True, to="accounts.student"),
        ),
    ]
