# Generated by Django 5.1 on 2025-02-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_lecturer_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_assigned",
            field=models.BooleanField(default=False),
        ),
    ]
