# Generated by Django 4.2.19 on 2025-03-10 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_fcmtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="program",
        ),
    ]
